// =============================================================================
// VIZION — Demo seed data (static, hardcoded)
// All IDs are deterministic strings — never use crypto.randomUUID() here.
// Dates are relative to 2026-05-07 (project date), expressed as ISO strings.
// =============================================================================

import type {
  DemoClientRow,
  DemoTrainerClientRow,
  DemoExerciseRow,
  DemoRoutineRow,
  DemoAssignedRoutineRow,
  DemoSessionRow,
  DemoMetricRow,
  DemoLocationRow,
  DemoLocationVisitRow,
  DemoExpenseRow,
  DemoSaleRow,
} from "@/lib/offline/db";

// ── Trainer ───────────────────────────────────────────────────────────────────

export const DEMO_TRAINER_ID = "trainer-demo-001";

// ── Clients ───────────────────────────────────────────────────────────────────

export const DEMO_CLIENTS: DemoClientRow[] = [
  {
    id: "client-ana",
    name: "Ana Solís Mora",
    email: "ana.solis@demo.local",
    avatarUrl: null,
    gender: "FEMALE",
    dateOfBirth: "1996-03-15",
    parqStatus: "GREEN",
    goal: "FAT_LOSS",
    weightKg: 68.5,
    heightCm: 165,
    locationCity: "San José",
    encryptedCedula: null,
    createdAt: "2025-08-01T00:00:00Z",
  },
  {
    id: "client-bruno",
    name: "Bruno Jiménez Rojas",
    email: "bruno.jimenez@demo.local",
    avatarUrl: null,
    gender: "MALE",
    dateOfBirth: "1994-07-22",
    parqStatus: "GREEN",
    goal: "MUSCLE_GAIN",
    weightKg: 83,
    heightCm: 178,
    locationCity: "Heredia",
    encryptedCedula: null,
    createdAt: "2025-09-10T00:00:00Z",
  },
  {
    id: "client-carlos",
    name: "Carlos Ulate Blanco",
    email: "carlos.ulate@demo.local",
    avatarUrl: null,
    gender: "MALE",
    dateOfBirth: "1988-11-30",
    parqStatus: "REVIEW",
    goal: "GENERAL_HEALTH",
    weightKg: 91,
    heightCm: 175,
    locationCity: "Cartago",
    encryptedCedula: null,
    createdAt: "2025-10-05T00:00:00Z",
  },
  {
    id: "client-diana",
    name: "Diana Mora Quesada",
    email: "diana.mora@demo.local",
    avatarUrl: null,
    gender: "FEMALE",
    dateOfBirth: "2000-01-18",
    parqStatus: "GREEN",
    goal: "PERFORMANCE",
    weightKg: 62,
    heightCm: 168,
    locationCity: "Alajuela",
    encryptedCedula: null,
    createdAt: "2025-11-20T00:00:00Z",
  },
];

// ── Trainer-client links ──────────────────────────────────────────────────────

export const DEMO_TRAINER_CLIENTS: DemoTrainerClientRow[] = [
  {
    id: "tc-ana",
    trainerUserId: DEMO_TRAINER_ID,
    clientUserId: "client-ana",
    status: "ACTIVE",
    monthlyPriceCRC: 75000,
    notesPrivate: "Ana es muy constante. Ajustar peso en sentadilla la próxima semana.",
    startedAt: "2025-08-01T00:00:00Z",
  },
  {
    id: "tc-bruno",
    trainerUserId: DEMO_TRAINER_ID,
    clientUserId: "client-bruno",
    status: "ACTIVE",
    monthlyPriceCRC: 80000,
    notesPrivate: "Bruno busca masa muscular. Aumentar proteínas en dieta.",
    startedAt: "2025-09-10T00:00:00Z",
  },
  {
    id: "tc-carlos",
    trainerUserId: DEMO_TRAINER_ID,
    clientUserId: "client-carlos",
    status: "ACTIVE",
    monthlyPriceCRC: 65000,
    notesPrivate: "Revisar PAR-Q con médico. Presión alta controlada con medicamento.",
    startedAt: "2025-10-05T00:00:00Z",
  },
  {
    id: "tc-diana",
    trainerUserId: DEMO_TRAINER_ID,
    clientUserId: "client-diana",
    status: "ACTIVE",
    monthlyPriceCRC: 70000,
    notesPrivate: "Diana compite en atletismo amateur. Enfocarse en potencia y velocidad.",
    startedAt: "2025-11-20T00:00:00Z",
  },
];

// ── Exercises (30 total) ──────────────────────────────────────────────────────

const BASE = process.env.NEXT_PUBLIC_BASE_PATH || "";
const IMG = `${BASE}/exercises`;

export const DEMO_EXERCISES: DemoExerciseRow[] = [
  // CHEST (4)
  {
    id: "ex-press-banca",
    slug: "press-de-banca-con-barra",
    nameEs: "Press de banca con barra",
    nameEn: "Barbell Bench Press",
    instructionsEs: "Acostado en banca plana, agarre medio. Bajá la barra controlado al pecho, exhalá empujando hacia arriba.",
    primaryMuscle: "CHEST",
    secondaryMuscles: ["TRICEPS", "SHOULDERS"],
    equipment: "BARBELL",
    difficulty: "INTERMEDIATE",
    gifUrl: null,
    thumbnailUrl: `${IMG}/barbell-bench-press.jpg`,
    createdById: null,
    isPublic: true,
  },
  {
    id: "ex-press-inclinado",
    slug: "press-inclinado-mancuernas",
    nameEs: "Press inclinado con mancuernas",
    nameEn: "Incline Dumbbell Press",
    instructionsEs: "Banca a 30-45°. Empujá las mancuernas hacia arriba y adentro controlando la bajada.",
    primaryMuscle: "CHEST",
    secondaryMuscles: ["TRICEPS", "SHOULDERS"],
    equipment: "DUMBBELL",
    difficulty: "INTERMEDIATE",
    gifUrl: null,
    thumbnailUrl: `${IMG}/incline-bench-press.jpg`,
    createdById: null,
    isPublic: true,
  },
  {
    id: "ex-aperturas",
    slug: "aperturas-mancuernas-plano",
    nameEs: "Aperturas con mancuernas en plano",
    nameEn: "Dumbbell Flyes",
    instructionsEs: "Banca plana. Brazos ligeramente flexionados. Bajá en arco amplio hasta sentir estiramiento en el pecho.",
    primaryMuscle: "CHEST",
    secondaryMuscles: [],
    equipment: "DUMBBELL",
    difficulty: "BEGINNER",
    gifUrl: null,
    thumbnailUrl: `${IMG}/dumbbell-fly.jpg`,
    createdById: null,
    isPublic: true,
  },
  {
    id: "ex-fondos",
    slug: "fondos-pecho",
    nameEs: "Fondos en paralelas (pecho)",
    nameEn: "Chest Dips",
    instructionsEs: "Inclinate ligeramente hacia adelante para enfatizar el pecho. Bajá hasta 90° en codos y subí.",
    primaryMuscle: "CHEST",
    secondaryMuscles: ["TRICEPS"],
    equipment: "BODY_WEIGHT",
    difficulty: "INTERMEDIATE",
    gifUrl: null,
    thumbnailUrl: `${IMG}/dips.jpg`,
    createdById: null,
    isPublic: true,
  },
  // BACK (4)
  {
    id: "ex-dominadas",
    slug: "dominadas-agarre-prono",
    nameEs: "Dominadas agarre prono",
    nameEn: "Pull-ups",
    instructionsEs: "Agarre prono ancho. Jalá el cuerpo hacia arriba hasta que el mentón supere la barra. Bajá controlado.",
    primaryMuscle: "BACK",
    secondaryMuscles: ["BICEPS"],
    equipment: "BODY_WEIGHT",
    difficulty: "INTERMEDIATE",
    gifUrl: null,
    thumbnailUrl: `${IMG}/pull-up.jpg`,
    createdById: null,
    isPublic: true,
  },
  {
    id: "ex-remo-barra",
    slug: "remo-con-barra",
    nameEs: "Remo con barra",
    nameEn: "Barbell Row",
    instructionsEs: "Torso casi paralelo al suelo. Jalá la barra hacia el abdomen, apretá los omóplatos. Bajá controlado.",
    primaryMuscle: "BACK",
    secondaryMuscles: ["BICEPS", "SHOULDERS"],
    equipment: "BARBELL",
    difficulty: "INTERMEDIATE",
    gifUrl: null,
    thumbnailUrl: `${IMG}/barbell-bent-over-row.jpg`,
    createdById: null,
    isPublic: true,
  },
  {
    id: "ex-jalon-polea",
    slug: "jalon-polea-agarre-amplio",
    nameEs: "Jalón en polea agarre amplio",
    nameEn: "Lat Pulldown",
    instructionsEs: "Sentado, agarre prono ancho. Jalá la barra hacia el pecho superior manteniendo el pecho elevado.",
    primaryMuscle: "BACK",
    secondaryMuscles: ["BICEPS"],
    equipment: "CABLE",
    difficulty: "BEGINNER",
    gifUrl: null,
    thumbnailUrl: `${IMG}/lat-pulldown.jpg`,
    createdById: null,
    isPublic: true,
  },
  {
    id: "ex-peso-muerto",
    slug: "peso-muerto-convencional",
    nameEs: "Peso muerto convencional",
    nameEn: "Conventional Deadlift",
    instructionsEs: "Pies al ancho de caderas, agarre doble prono. Empujá el suelo con los pies, jalá la barra pegada al cuerpo manteniendo espalda neutra.",
    primaryMuscle: "BACK",
    secondaryMuscles: ["HAMSTRINGS", "GLUTES", "QUADS"],
    equipment: "BARBELL",
    difficulty: "ADVANCED",
    gifUrl: null,
    thumbnailUrl: `${IMG}/deadlift.jpg`,
    createdById: null,
    isPublic: true,
  },
  // SHOULDERS (3)
  {
    id: "ex-press-militar",
    slug: "press-militar-con-barra",
    nameEs: "Press militar con barra",
    nameEn: "Overhead Press",
    instructionsEs: "De pie o sentado. Barra a nivel de clavículas, empujá hacia arriba hasta brazos extendidos. Bajá controlado.",
    primaryMuscle: "SHOULDERS",
    secondaryMuscles: ["TRICEPS"],
    equipment: "BARBELL",
    difficulty: "INTERMEDIATE",
    gifUrl: null,
    thumbnailUrl: `${IMG}/overhead-press.jpg`,
    createdById: null,
    isPublic: true,
  },
  {
    id: "ex-elevaciones-laterales",
    slug: "elevaciones-laterales-mancuernas",
    nameEs: "Elevaciones laterales con mancuernas",
    nameEn: "Lateral Raises",
    instructionsEs: "De pie, brazos ligeramente flexionados. Levantá las mancuernas lateralmente hasta nivel de hombros.",
    primaryMuscle: "SHOULDERS",
    secondaryMuscles: [],
    equipment: "DUMBBELL",
    difficulty: "BEGINNER",
    gifUrl: null,
    thumbnailUrl: `${IMG}/dumbbell-lateral-raise.jpg`,
    createdById: null,
    isPublic: true,
  },
  {
    id: "ex-press-arnold",
    slug: "press-arnold",
    nameEs: "Press Arnold",
    nameEn: "Arnold Press",
    instructionsEs: "Empezá con las palmas hacia vos. Al subir, rotá las muñecas hacia afuera. Bajá invirtiendo el movimiento.",
    primaryMuscle: "SHOULDERS",
    secondaryMuscles: ["TRICEPS"],
    equipment: "DUMBBELL",
    difficulty: "INTERMEDIATE",
    gifUrl: null,
    thumbnailUrl: `${IMG}/arnold-press.jpg`,
    createdById: null,
    isPublic: true,
  },
  // BICEPS (2)
  {
    id: "ex-curl-barra",
    slug: "curl-de-biceps-con-barra",
    nameEs: "Curl de bíceps con barra",
    nameEn: "Barbell Bicep Curl",
    instructionsEs: "De pie, agarre supino. Flexioná los codos llevando la barra hacia los hombros. Bajá controlado.",
    primaryMuscle: "BICEPS",
    secondaryMuscles: [],
    equipment: "BARBELL",
    difficulty: "BEGINNER",
    gifUrl: null,
    thumbnailUrl: `${IMG}/barbell-curl.jpg`,
    createdById: null,
    isPublic: true,
  },
  {
    id: "ex-curl-martillo",
    slug: "curl-martillo-mancuernas",
    nameEs: "Curl martillo con mancuernas",
    nameEn: "Hammer Curl",
    instructionsEs: "Agarre neutro (pulgar arriba). Flexioná el codo sin rotar la muñeca.",
    primaryMuscle: "BICEPS",
    secondaryMuscles: ["FOREARMS"],
    equipment: "DUMBBELL",
    difficulty: "BEGINNER",
    gifUrl: null,
    thumbnailUrl: `${IMG}/hammer-curl.jpg`,
    createdById: null,
    isPublic: true,
  },
  // TRICEPS (2)
  {
    id: "ex-extensiones-triceps",
    slug: "extensiones-triceps-polea",
    nameEs: "Extensiones de tríceps en polea",
    nameEn: "Cable Triceps Pushdown",
    instructionsEs: "De pie frente a polea alta. Codos pegados al cuerpo, extendes los brazos hacia abajo completamente.",
    primaryMuscle: "TRICEPS",
    secondaryMuscles: [],
    equipment: "CABLE",
    difficulty: "BEGINNER",
    gifUrl: null,
    thumbnailUrl: `${IMG}/cable-pushdown.jpg`,
    createdById: null,
    isPublic: true,
  },
  {
    id: "ex-fondos-triceps",
    slug: "fondos-triceps-banco",
    nameEs: "Fondos de tríceps en banco",
    nameEn: "Bench Dips",
    instructionsEs: "Manos en el borde del banco, pies extendidos. Bajá doblando los codos a 90° y subí.",
    primaryMuscle: "TRICEPS",
    secondaryMuscles: [],
    equipment: "BODY_WEIGHT",
    difficulty: "BEGINNER",
    gifUrl: null,
    thumbnailUrl: `${IMG}/bench-dip.jpg`,
    createdById: null,
    isPublic: true,
  },
  // QUADS (3)
  {
    id: "ex-sentadilla",
    slug: "sentadilla-con-barra",
    nameEs: "Sentadilla con barra",
    nameEn: "Back Squat",
    instructionsEs: "Barra en trapecio, pies al ancho de hombros. Bajá manteniendo el torso erguido hasta paralelo o más. Subí empujando el suelo.",
    primaryMuscle: "QUADS",
    secondaryMuscles: ["GLUTES", "HAMSTRINGS"],
    equipment: "BARBELL",
    difficulty: "INTERMEDIATE",
    gifUrl: null,
    thumbnailUrl: `${IMG}/barbell-back-squat.jpg`,
    createdById: null,
    isPublic: true,
  },
  {
    id: "ex-prensa",
    slug: "prensa-de-piernas",
    nameEs: "Prensa de piernas",
    nameEn: "Leg Press",
    instructionsEs: "Pies al ancho de hombros en la plataforma. Bajá el peso controlado hasta 90° y empujá.",
    primaryMuscle: "QUADS",
    secondaryMuscles: ["GLUTES"],
    equipment: "MACHINE",
    difficulty: "BEGINNER",
    gifUrl: null,
    thumbnailUrl: `${IMG}/leg-press.jpg`,
    createdById: null,
    isPublic: true,
  },
  {
    id: "ex-extension-cuadriceps",
    slug: "extension-de-cuadriceps-maquina",
    nameEs: "Extensión de cuádriceps en máquina",
    nameEn: "Leg Extension",
    instructionsEs: "Sentado en la máquina. Extendes las piernas hasta contraer completamente el cuádriceps. Bajá controlado.",
    primaryMuscle: "QUADS",
    secondaryMuscles: [],
    equipment: "MACHINE",
    difficulty: "BEGINNER",
    gifUrl: null,
    thumbnailUrl: `${IMG}/leg-extension.jpg`,
    createdById: null,
    isPublic: true,
  },
  // HAMSTRINGS (2)
  {
    id: "ex-curl-femoral",
    slug: "curl-femoral-tumbado",
    nameEs: "Curl femoral tumbado",
    nameEn: "Lying Leg Curl",
    instructionsEs: "Boca abajo en la máquina. Contraé los isquios jalando el peso hacia los glúteos.",
    primaryMuscle: "HAMSTRINGS",
    secondaryMuscles: [],
    equipment: "MACHINE",
    difficulty: "BEGINNER",
    gifUrl: null,
    thumbnailUrl: `${IMG}/lying-leg-curl.jpg`,
    createdById: null,
    isPublic: true,
  },
  {
    id: "ex-peso-muerto-rumano",
    slug: "peso-muerto-rumano",
    nameEs: "Peso muerto rumano",
    nameEn: "Romanian Deadlift",
    instructionsEs: "De pie con barra. Inclinás el torso hacia adelante manteniendo espalda recta hasta sentir estiramiento en isquios. Subí contrayendo glúteos.",
    primaryMuscle: "HAMSTRINGS",
    secondaryMuscles: ["GLUTES", "BACK"],
    equipment: "BARBELL",
    difficulty: "INTERMEDIATE",
    gifUrl: null,
    thumbnailUrl: `${IMG}/romanian-deadlift.jpg`,
    createdById: null,
    isPublic: true,
  },
  // GLUTES (2)
  {
    id: "ex-hip-thrust",
    slug: "hip-thrust-con-barra",
    nameEs: "Hip thrust con barra",
    nameEn: "Hip Thrust",
    instructionsEs: "Espalda apoyada en banca, barra en caderas. Empujá las caderas hacia arriba contrayendo glúteos. Mantené un segundo arriba.",
    primaryMuscle: "GLUTES",
    secondaryMuscles: ["HAMSTRINGS"],
    equipment: "BARBELL",
    difficulty: "INTERMEDIATE",
    gifUrl: null,
    thumbnailUrl: `${IMG}/hip-thrust.jpg`,
    createdById: null,
    isPublic: true,
  },
  {
    id: "ex-zancadas",
    slug: "zancadas-mancuernas",
    nameEs: "Zancadas con mancuernas",
    nameEn: "Dumbbell Lunges",
    instructionsEs: "Un paso largo adelante, bajá la rodilla trasera casi al suelo. Subí y alternás piernas.",
    primaryMuscle: "GLUTES",
    secondaryMuscles: ["QUADS", "HAMSTRINGS"],
    equipment: "DUMBBELL",
    difficulty: "BEGINNER",
    gifUrl: null,
    thumbnailUrl: `${IMG}/barbell-lunge.jpg`,
    createdById: null,
    isPublic: true,
  },
  // CALVES (2)
  {
    id: "ex-elevaciones-gemelos",
    slug: "elevaciones-de-gemelos-maquina",
    nameEs: "Elevaciones de gemelos en máquina",
    nameEn: "Standing Calf Raise",
    instructionsEs: "De pie en la máquina, elevá los talones lo más alto posible. Bajá hasta sentir estiramiento.",
    primaryMuscle: "CALVES",
    secondaryMuscles: [],
    equipment: "MACHINE",
    difficulty: "BEGINNER",
    gifUrl: null,
    thumbnailUrl: `${IMG}/standing-calf-raise.jpg`,
    createdById: null,
    isPublic: true,
  },
  {
    id: "ex-gemelos-sentado",
    slug: "elevaciones-gemelos-sentado",
    nameEs: "Elevaciones de gemelos sentado",
    nameEn: "Seated Calf Raise",
    instructionsEs: "Sentado, rodillas a 90°. Elevá los talones contrayendo el soleo.",
    primaryMuscle: "CALVES",
    secondaryMuscles: [],
    equipment: "MACHINE",
    difficulty: "BEGINNER",
    gifUrl: null,
    thumbnailUrl: `${IMG}/seated-calf-raise.jpg`,
    createdById: null,
    isPublic: true,
  },
  // ABS (3)
  {
    id: "ex-plancha",
    slug: "plancha-isometrica",
    nameEs: "Plancha isométrica",
    nameEn: "Plank",
    instructionsEs: "Apoyado en antebrazos y puntas de pies. Cuerpo en línea recta. Mantené la posición.",
    primaryMuscle: "ABS",
    secondaryMuscles: [],
    equipment: "BODY_WEIGHT",
    difficulty: "BEGINNER",
    gifUrl: null,
    thumbnailUrl: `${IMG}/plank.jpg`,
    createdById: null,
    isPublic: true,
  },
  {
    id: "ex-crunch",
    slug: "crunch-abdominal",
    nameEs: "Crunch abdominal",
    nameEn: "Crunch",
    instructionsEs: "Tumbado boca arriba, rodillas flexionadas. Contraé el abdomen elevando los hombros del suelo.",
    primaryMuscle: "ABS",
    secondaryMuscles: [],
    equipment: "BODY_WEIGHT",
    difficulty: "BEGINNER",
    gifUrl: null,
    thumbnailUrl: `${IMG}/crunch.jpg`,
    createdById: null,
    isPublic: true,
  },
  {
    id: "ex-rueda-abdomen",
    slug: "rueda-de-abdomen",
    nameEs: "Rueda de abdomen",
    nameEn: "Ab Wheel Rollout",
    instructionsEs: "De rodillas, rodá la rueda hacia adelante manteniendo el core tenso. Jalá de vuelta contrayendo el abdomen.",
    primaryMuscle: "ABS",
    secondaryMuscles: ["BACK"],
    equipment: "OTHER",
    difficulty: "ADVANCED",
    gifUrl: null,
    thumbnailUrl: `${IMG}/ab-rollout.jpg`,
    createdById: null,
    isPublic: true,
  },
  // FULL_BODY (2)
  {
    id: "ex-burpee",
    slug: "burpee",
    nameEs: "Burpee",
    nameEn: "Burpee",
    instructionsEs: "Desde de pie: bajá a plancha, hacé una flexión, jalá los pies, saltá con los brazos arriba.",
    primaryMuscle: "FULL_BODY",
    secondaryMuscles: [],
    equipment: "BODY_WEIGHT",
    difficulty: "INTERMEDIATE",
    gifUrl: null,
    thumbnailUrl: null,
    createdById: null,
    isPublic: true,
  },
  {
    id: "ex-clean-press",
    slug: "clean-and-press-mancuernas",
    nameEs: "Clean y press con mancuernas",
    nameEn: "Dumbbell Clean and Press",
    instructionsEs: "Jalá las mancuernas desde el suelo hasta los hombros (clean) y luego presioná sobre la cabeza.",
    primaryMuscle: "FULL_BODY",
    secondaryMuscles: ["SHOULDERS", "BACK", "QUADS"],
    equipment: "DUMBBELL",
    difficulty: "ADVANCED",
    gifUrl: null,
    thumbnailUrl: `${IMG}/dumbbell-clean-and-press.jpg`,
    createdById: null,
    isPublic: true,
  },
  // ── Programa Macho — new exercises ─────────────────────────────────────────
  {
    id: "ex-press-militar-manc",
    slug: "press-militar-mancuernas",
    nameEs: "Press militar con mancuernas",
    nameEn: "Dumbbell Shoulder Press",
    instructionsEs: "Sentado o de pie, mancuernas a nivel de hombros con palmas al frente. Empujá hacia arriba hasta extender los brazos. Bajá controlado.",
    primaryMuscle: "SHOULDERS",
    secondaryMuscles: ["TRICEPS"],
    equipment: "DUMBBELL",
    difficulty: "INTERMEDIATE",
    gifUrl: null,
    thumbnailUrl: null,
    createdById: null,
    isPublic: true,
  },
  {
    id: "ex-remo-mancuerna",
    slug: "remo-con-mancuerna",
    nameEs: "Remo con mancuerna",
    nameEn: "Dumbbell Row",
    instructionsEs: "Una rodilla y mano en banca. Jalá la mancuerna hacia la cadera, apretá el omóplato arriba. Bajá controlado.",
    primaryMuscle: "BACK",
    secondaryMuscles: ["BICEPS"],
    equipment: "DUMBBELL",
    difficulty: "BEGINNER",
    gifUrl: null,
    thumbnailUrl: null,
    createdById: null,
    isPublic: true,
  },
  {
    id: "ex-pullover-mancuerna",
    slug: "pullover-mancuerna",
    nameEs: "Pullover con mancuerna",
    nameEn: "Dumbbell Pullover",
    instructionsEs: "Acostado en banca, sostené una mancuerna con ambas manos sobre el pecho. Bajá detrás de la cabeza con brazos ligeramente flexionados. Subí contrayendo pecho y dorsal.",
    primaryMuscle: "BACK",
    secondaryMuscles: ["CHEST"],
    equipment: "DUMBBELL",
    difficulty: "INTERMEDIATE",
    gifUrl: null,
    thumbnailUrl: null,
    createdById: null,
    isPublic: true,
  },
  {
    id: "ex-curl-mancuerna",
    slug: "curl-biceps-mancuerna",
    nameEs: "Curl de bíceps con mancuerna",
    nameEn: "Dumbbell Bicep Curl",
    instructionsEs: "De pie, mancuernas a los lados con agarre supino. Flexioná los codos alternando o simultáneamente. Bajá controlado.",
    primaryMuscle: "BICEPS",
    secondaryMuscles: [],
    equipment: "DUMBBELL",
    difficulty: "BEGINNER",
    gifUrl: null,
    thumbnailUrl: null,
    createdById: null,
    isPublic: true,
  },
  {
    id: "ex-remo-cuello",
    slug: "remo-al-cuello-barra-z",
    nameEs: "Remo al cuello con barra Z",
    nameEn: "EZ Bar Upright Row",
    instructionsEs: "De pie, agarre cerrado en barra Z. Jalá la barra hacia el mentón elevando los codos. Bajá controlado.",
    primaryMuscle: "SHOULDERS",
    secondaryMuscles: ["BICEPS"],
    equipment: "BARBELL",
    difficulty: "INTERMEDIATE",
    gifUrl: null,
    thumbnailUrl: null,
    createdById: null,
    isPublic: true,
  },
  {
    id: "ex-biceps-hold",
    slug: "biceps-hold-isometrico",
    nameEs: "Bíceps hold isométrico",
    nameEn: "Isometric Bicep Hold",
    instructionsEs: "Curl a 90° y mantené la posición isométrica el tiempo indicado. Controlá la respiración.",
    primaryMuscle: "BICEPS",
    secondaryMuscles: ["FOREARMS"],
    equipment: "DUMBBELL",
    difficulty: "BEGINNER",
    gifUrl: null,
    thumbnailUrl: null,
    createdById: null,
    isPublic: true,
  },
  {
    id: "ex-desplante-bulgaro",
    slug: "desplante-bulgaro-mancuerna",
    nameEs: "Desplante búlgaro con mancuerna",
    nameEn: "Bulgarian Split Squat",
    instructionsEs: "Pie trasero elevado en banca. Bajá la rodilla trasera hacia el suelo manteniendo el torso recto. Subí empujando con la pierna delantera.",
    primaryMuscle: "QUADS",
    secondaryMuscles: ["GLUTES", "HAMSTRINGS"],
    equipment: "DUMBBELL",
    difficulty: "INTERMEDIATE",
    gifUrl: null,
    thumbnailUrl: null,
    createdById: null,
    isPublic: true,
  },
  {
    id: "ex-salto-sentadilla",
    slug: "salto-con-sentadilla",
    nameEs: "Salto con sentadilla",
    nameEn: "Jump Squat",
    instructionsEs: "Sentadilla a paralelo y saltá explosivamente. Aterrizá suave con rodillas ligeramente flexionadas.",
    primaryMuscle: "QUADS",
    secondaryMuscles: ["GLUTES", "CALVES"],
    equipment: "BODY_WEIGHT",
    difficulty: "INTERMEDIATE",
    gifUrl: null,
    thumbnailUrl: null,
    createdById: null,
    isPublic: true,
  },
  {
    id: "ex-sentadilla-isometrica",
    slug: "sentadilla-isometrica-pared",
    nameEs: "Sentadilla isométrica",
    nameEn: "Wall Sit",
    instructionsEs: "Espalda contra la pared, bajá hasta que los muslos queden paralelos al suelo. Mantené la posición el tiempo indicado.",
    primaryMuscle: "QUADS",
    secondaryMuscles: ["GLUTES"],
    equipment: "BODY_WEIGHT",
    difficulty: "BEGINNER",
    gifUrl: null,
    thumbnailUrl: null,
    createdById: null,
    isPublic: true,
  },
  {
    id: "ex-step-up",
    slug: "step-up-banco",
    nameEs: "Step up en banco",
    nameEn: "Step Up",
    instructionsEs: "Subí a un banco con una pierna, extendé la cadera arriba. Bajá controlado y alterná piernas.",
    primaryMuscle: "QUADS",
    secondaryMuscles: ["GLUTES", "HAMSTRINGS"],
    equipment: "DUMBBELL",
    difficulty: "BEGINNER",
    gifUrl: null,
    thumbnailUrl: null,
    createdById: null,
    isPublic: true,
  },
  {
    id: "ex-elevacion-talon-smith",
    slug: "elevacion-talon-smith",
    nameEs: "Elevación de talón en Smith",
    nameEn: "Smith Machine Calf Raise",
    instructionsEs: "En máquina Smith, puntas de los pies en plataforma elevada. Elevá los talones lo más alto posible, bajá lento.",
    primaryMuscle: "CALVES",
    secondaryMuscles: [],
    equipment: "MACHINE",
    difficulty: "BEGINNER",
    gifUrl: null,
    thumbnailUrl: null,
    createdById: null,
    isPublic: true,
  },
  {
    id: "ex-russian-twist",
    slug: "russian-twist",
    nameEs: "Russian twist",
    nameEn: "Russian Twist",
    instructionsEs: "Sentado con torso a 45°, pies elevados. Rotá el torso de lado a lado tocando el suelo con las manos o peso.",
    primaryMuscle: "ABS",
    secondaryMuscles: ["OBLIQUES"],
    equipment: "BODY_WEIGHT",
    difficulty: "BEGINNER",
    gifUrl: null,
    thumbnailUrl: null,
    createdById: null,
    isPublic: true,
  },
];

// ── Routines ──────────────────────────────────────────────────────────────────────

export const DEMO_ROUTINES: DemoRoutineRow[] = [
  // Programa Macho — 3 días PPL, 8 semanas, hipertrofia
  {
    id: "routine-programa-macho",
    trainerId: DEMO_TRAINER_ID,
    name: "Programa Macho",
    description: "Push-Pull-Legs de 3 días enfocado en hipertrofia. Supersets (A/B) para máxima intensidad. Abdominales 2x/semana al final del entreno.",
    goal: "HYPERTROPHY",
    splitDays: 3,
    durationWeeks: 8,
    isArchived: false,
    createdAt: "2026-04-01T00:00:00Z",
    updatedAt: "2026-04-01T00:00:00Z",
    daysJson: [
      {
        id: "pm-d0",
        dayIndex: 0,
        name: "Día 1 — Push (Pecho + Hombros + Tríceps)",
        exercises: [
          { id: "pm-d0-e0", exerciseId: "ex-press-banca", order: 0, targetSets: 4, targetRepsMin: 10, targetRepsMax: 10, targetRpe: 8, restSeconds: 90, tempo: null, notes: "Superset con 1B Aperturas" },
          { id: "pm-d0-e1", exerciseId: "ex-aperturas", order: 1, targetSets: 4, targetRepsMin: 12, targetRepsMax: 12, targetRpe: 7, restSeconds: 90, tempo: null, notes: "Superset con 1A Press plano" },
          { id: "pm-d0-e2", exerciseId: "ex-press-militar-manc", order: 2, targetSets: 4, targetRepsMin: 12, targetRepsMax: 12, targetRpe: 8, restSeconds: 90, tempo: null, notes: "Superset con 2B Elevaciones laterales" },
          { id: "pm-d0-e3", exerciseId: "ex-elevaciones-laterales", order: 3, targetSets: 4, targetRepsMin: 10, targetRepsMax: 10, targetRpe: 7, restSeconds: 90, tempo: null, notes: "Superset con 2A Press militar" },
          { id: "pm-d0-e4", exerciseId: "ex-extensiones-triceps", order: 4, targetSets: 4, targetRepsMin: 12, targetRepsMax: 12, targetRpe: 7, restSeconds: 60, tempo: null, notes: "Superset con 3B Fondos en banco" },
          { id: "pm-d0-e5", exerciseId: "ex-fondos-triceps", order: 5, targetSets: 4, targetRepsMin: 12, targetRepsMax: 12, targetRpe: 7, restSeconds: 60, tempo: null, notes: "Superset con 3A Extensión mecate" },
          { id: "pm-d0-e6", exerciseId: "ex-plancha", order: 6, targetSets: 3, targetRepsMin: 60, targetRepsMax: 60, targetRpe: null, restSeconds: 60, tempo: null, notes: "segundos — Bloque abdomen" },
          { id: "pm-d0-e7", exerciseId: "ex-russian-twist", order: 7, targetSets: 3, targetRepsMin: 20, targetRepsMax: 20, targetRpe: null, restSeconds: 45, tempo: null, notes: "Bloque abdomen" },
          { id: "pm-d0-e8", exerciseId: "ex-crunch", order: 8, targetSets: 3, targetRepsMin: 20, targetRepsMax: 20, targetRpe: null, restSeconds: 45, tempo: null, notes: "Bloque abdomen" },
        ],
      },
      {
        id: "pm-d1",
        dayIndex: 1,
        name: "Día 2 — Pull (Espalda + Bíceps)",
        exercises: [
          { id: "pm-d1-e0", exerciseId: "ex-remo-mancuerna", order: 0, targetSets: 5, targetRepsMin: 12, targetRepsMax: 12, targetRpe: 8, restSeconds: 90, tempo: null, notes: null },
          { id: "pm-d1-e1", exerciseId: "ex-pullover-mancuerna", order: 1, targetSets: 5, targetRepsMin: 10, targetRepsMax: 10, targetRpe: 8, restSeconds: 90, tempo: null, notes: null },
          { id: "pm-d1-e2", exerciseId: "ex-curl-mancuerna", order: 2, targetSets: 4, targetRepsMin: 12, targetRepsMax: 12, targetRpe: 7, restSeconds: 60, tempo: null, notes: "Superset con 3B Curl martillo" },
          { id: "pm-d1-e3", exerciseId: "ex-curl-martillo", order: 3, targetSets: 4, targetRepsMin: 12, targetRepsMax: 12, targetRpe: 7, restSeconds: 60, tempo: null, notes: "Superset con 3A Curl mancuerna" },
          { id: "pm-d1-e4", exerciseId: "ex-remo-cuello", order: 4, targetSets: 4, targetRepsMin: 10, targetRepsMax: 10, targetRpe: 7, restSeconds: 90, tempo: null, notes: null },
          { id: "pm-d1-e5", exerciseId: "ex-biceps-hold", order: 5, targetSets: 3, targetRepsMin: 10, targetRepsMax: 10, targetRpe: null, restSeconds: 60, tempo: null, notes: "segundos de hold isométrico" },
        ],
      },
      {
        id: "pm-d2",
        dayIndex: 2,
        name: "Día 3 — Piernas",
        exercises: [
          { id: "pm-d2-e0", exerciseId: "ex-desplante-bulgaro", order: 0, targetSets: 4, targetRepsMin: 12, targetRepsMax: 12, targetRpe: 8, restSeconds: 60, tempo: null, notes: "Superset con 1B Salto sentadilla" },
          { id: "pm-d2-e1", exerciseId: "ex-salto-sentadilla", order: 1, targetSets: 4, targetRepsMin: 12, targetRepsMax: 12, targetRpe: 8, restSeconds: 90, tempo: null, notes: "Superset con 1A Desplante búlgaro" },
          { id: "pm-d2-e2", exerciseId: "ex-sentadilla-isometrica", order: 2, targetSets: 4, targetRepsMin: 60, targetRepsMax: 60, targetRpe: null, restSeconds: 60, tempo: null, notes: "segundos de hold isométrico" },
          { id: "pm-d2-e3", exerciseId: "ex-step-up", order: 3, targetSets: 4, targetRepsMin: 12, targetRepsMax: 12, targetRpe: 7, restSeconds: 90, tempo: null, notes: null },
          { id: "pm-d2-e4", exerciseId: "ex-prensa", order: 4, targetSets: 4, targetRepsMin: 12, targetRepsMax: 12, targetRpe: 8, restSeconds: 90, tempo: null, notes: null },
          { id: "pm-d2-e5", exerciseId: "ex-elevacion-talon-smith", order: 5, targetSets: 4, targetRepsMin: 30, targetRepsMax: 30, targetRpe: null, restSeconds: 60, tempo: null, notes: null },
          { id: "pm-d2-e6", exerciseId: "ex-plancha", order: 6, targetSets: 3, targetRepsMin: 60, targetRepsMax: 60, targetRpe: null, restSeconds: 60, tempo: null, notes: "segundos — Bloque abdomen" },
          { id: "pm-d2-e7", exerciseId: "ex-russian-twist", order: 7, targetSets: 3, targetRepsMin: 20, targetRepsMax: 20, targetRpe: null, restSeconds: 45, tempo: null, notes: "Bloque abdomen" },
          { id: "pm-d2-e8", exerciseId: "ex-crunch", order: 8, targetSets: 3, targetRepsMin: 20, targetRepsMax: 20, targetRpe: null, restSeconds: 45, tempo: null, notes: "Bloque abdomen" },
        ],
      },
    ],
  },
];

// ── Assigned routines ─────────────────────────────────────────────────────────────────

export const DEMO_ASSIGNED_ROUTINES: DemoAssignedRoutineRow[] = [
  {
    id: "ar-ana-macho",
    clientUserId: "client-ana",
    routineTemplateId: "routine-programa-macho",
    startsOn: "2026-03-10",
    endsOn: "2026-05-05",
    status: "ACTIVE",
    snapshotJson: { templateId: "routine-programa-macho", templateName: "Programa Macho", splitDays: 3, durationWeeks: 8, snapshotAt: "2026-03-10T00:00:00Z" },
  },
  {
    id: "ar-bruno-macho",
    clientUserId: "client-bruno",
    routineTemplateId: "routine-programa-macho",
    startsOn: "2026-03-17",
    endsOn: "2026-05-12",
    status: "ACTIVE",
    snapshotJson: { templateId: "routine-programa-macho", templateName: "Programa Macho", splitDays: 3, durationWeeks: 8, snapshotAt: "2026-03-17T00:00:00Z" },
  },
  {
    id: "ar-carlos-macho",
    clientUserId: "client-carlos",
    routineTemplateId: "routine-programa-macho",
    startsOn: "2026-03-24",
    endsOn: "2026-05-19",
    status: "ACTIVE",
    snapshotJson: { templateId: "routine-programa-macho", templateName: "Programa Macho", splitDays: 3, durationWeeks: 8, snapshotAt: "2026-03-24T00:00:00Z" },
  },
  {
    id: "ar-diana-macho",
    clientUserId: "client-diana",
    routineTemplateId: "routine-programa-macho",
    startsOn: "2026-03-10",
    endsOn: "2026-05-05",
    status: "ACTIVE",
    snapshotJson: { templateId: "routine-programa-macho", templateName: "Programa Macho", splitDays: 3, durationWeeks: 8, snapshotAt: "2026-03-10T00:00:00Z" },
  },
];

// ── Sessions (helper to generate past date strings) ─────────────────────────────────────────

function daysAgo(n: number): string {
  const d = new Date("2026-05-07T00:00:00Z");
  d.setDate(d.getDate() - n);
  return d.toISOString();
}

// Ana: 9 sessions (highly adherent, last 30 days)
// Bruno: 5 sessions (decent adherence)
// Carlos, Diana: 0 sessions (for alert generation)

export const DEMO_SESSIONS: DemoSessionRow[] = [
  // Ana sessions — Programa Macho, progressing bench press 30 → 35 kg
  {
    id: "sess-ana-01",
    clientUserId: "client-ana",
    assignedRoutineId: "ar-ana-macho",
    dayIndex: 0,
    status: "COMPLETED",
    startedAt: daysAgo(28),
    completedAt: daysAgo(28),
    totalDurationSec: 4200,
    bodyweightKg: 69.5,
    subjectiveFatigue: 3,
    notes: null,
    isFreeWorkout: false,
    setsJson: [
      { id: "s-a01-1", exerciseId: "ex-press-banca", setNumber: 1, weightKg: 30, reps: 10, rpe: 7, isWarmup: false, isPr: false },
      { id: "s-a01-2", exerciseId: "ex-press-banca", setNumber: 2, weightKg: 30, reps: 10, rpe: 7, isWarmup: false, isPr: false },
      { id: "s-a01-3", exerciseId: "ex-press-banca", setNumber: 3, weightKg: 30, reps: 9, rpe: 8, isWarmup: false, isPr: false },
      { id: "s-a01-4", exerciseId: "ex-aperturas", setNumber: 1, weightKg: 8, reps: 12, rpe: 7, isWarmup: false, isPr: false },
      { id: "s-a01-5", exerciseId: "ex-aperturas", setNumber: 2, weightKg: 8, reps: 12, rpe: 7, isWarmup: false, isPr: false },
    ],
  },
  {
    id: "sess-ana-02",
    clientUserId: "client-ana",
    assignedRoutineId: "ar-ana-macho",
    dayIndex: 1,
    status: "COMPLETED",
    startedAt: daysAgo(26),
    completedAt: daysAgo(26),
    totalDurationSec: 3900,
    bodyweightKg: 69.2,
    subjectiveFatigue: 3,
    notes: null,
    isFreeWorkout: false,
    setsJson: [
      { id: "s-a02-1", exerciseId: "ex-remo-mancuerna", setNumber: 1, weightKg: 12, reps: 12, rpe: 7, isWarmup: false, isPr: false },
      { id: "s-a02-2", exerciseId: "ex-remo-mancuerna", setNumber: 2, weightKg: 12, reps: 12, rpe: 8, isWarmup: false, isPr: false },
      { id: "s-a02-3", exerciseId: "ex-curl-mancuerna", setNumber: 1, weightKg: 6, reps: 12, rpe: 7, isWarmup: false, isPr: false },
      { id: "s-a02-4", exerciseId: "ex-curl-martillo", setNumber: 1, weightKg: 6, reps: 12, rpe: 7, isWarmup: false, isPr: false },
    ],
  },
  {
    id: "sess-ana-03",
    clientUserId: "client-ana",
    assignedRoutineId: "ar-ana-macho",
    dayIndex: 2,
    status: "COMPLETED",
    startedAt: daysAgo(24),
    completedAt: daysAgo(24),
    totalDurationSec: 4500,
    bodyweightKg: 69.0,
    subjectiveFatigue: 4,
    notes: "Desplantes se sienten bien hoy",
    isFreeWorkout: false,
    setsJson: [
      { id: "s-a03-1", exerciseId: "ex-desplante-bulgaro", setNumber: 1, weightKg: 10, reps: 12, rpe: 7, isWarmup: false, isPr: false },
      { id: "s-a03-2", exerciseId: "ex-desplante-bulgaro", setNumber: 2, weightKg: 10, reps: 12, rpe: 8, isWarmup: false, isPr: false },
      { id: "s-a03-3", exerciseId: "ex-prensa", setNumber: 1, weightKg: 80, reps: 12, rpe: 7, isWarmup: false, isPr: false },
      { id: "s-a03-4", exerciseId: "ex-prensa", setNumber: 2, weightKg: 80, reps: 12, rpe: 8, isWarmup: false, isPr: false },
    ],
  },
  {
    id: "sess-ana-04",
    clientUserId: "client-ana",
    assignedRoutineId: "ar-ana-macho",
    dayIndex: 0,
    status: "COMPLETED",
    startedAt: daysAgo(21),
    completedAt: daysAgo(21),
    totalDurationSec: 4200,
    bodyweightKg: 68.8,
    subjectiveFatigue: 2,
    notes: null,
    isFreeWorkout: false,
    setsJson: [
      { id: "s-a04-1", exerciseId: "ex-press-banca", setNumber: 1, weightKg: 30, reps: 10, rpe: 7, isWarmup: false, isPr: false },
      { id: "s-a04-2", exerciseId: "ex-press-banca", setNumber: 2, weightKg: 32.5, reps: 10, rpe: 8, isWarmup: false, isPr: false },
      { id: "s-a04-3", exerciseId: "ex-press-militar-manc", setNumber: 1, weightKg: 8, reps: 12, rpe: 7, isWarmup: false, isPr: false },
      { id: "s-a04-4", exerciseId: "ex-press-militar-manc", setNumber: 2, weightKg: 8, reps: 12, rpe: 8, isWarmup: false, isPr: false },
    ],
  },
  {
    id: "sess-ana-05",
    clientUserId: "client-ana",
    assignedRoutineId: "ar-ana-macho",
    dayIndex: 1,
    status: "COMPLETED",
    startedAt: daysAgo(19),
    completedAt: daysAgo(19),
    totalDurationSec: 3600,
    bodyweightKg: 68.8,
    subjectiveFatigue: 3,
    notes: null,
    isFreeWorkout: false,
    setsJson: [
      { id: "s-a05-1", exerciseId: "ex-remo-mancuerna", setNumber: 1, weightKg: 14, reps: 12, rpe: 7, isWarmup: false, isPr: false },
      { id: "s-a05-2", exerciseId: "ex-remo-mancuerna", setNumber: 2, weightKg: 14, reps: 12, rpe: 8, isWarmup: false, isPr: false },
      { id: "s-a05-3", exerciseId: "ex-pullover-mancuerna", setNumber: 1, weightKg: 10, reps: 10, rpe: 7, isWarmup: false, isPr: false },
    ],
  },
  {
    id: "sess-ana-06",
    clientUserId: "client-ana",
    assignedRoutineId: "ar-ana-macho",
    dayIndex: 2,
    status: "COMPLETED",
    startedAt: daysAgo(17),
    completedAt: daysAgo(17),
    totalDurationSec: 4500,
    bodyweightKg: 68.5,
    subjectiveFatigue: 3,
    notes: null,
    isFreeWorkout: false,
    setsJson: [
      { id: "s-a06-1", exerciseId: "ex-desplante-bulgaro", setNumber: 1, weightKg: 12, reps: 12, rpe: 7, isWarmup: false, isPr: false },
      { id: "s-a06-2", exerciseId: "ex-desplante-bulgaro", setNumber: 2, weightKg: 12, reps: 12, rpe: 8, isWarmup: false, isPr: true },
      { id: "s-a06-3", exerciseId: "ex-prensa", setNumber: 1, weightKg: 85, reps: 12, rpe: 8, isWarmup: false, isPr: false },
    ],
  },
  {
    id: "sess-ana-07",
    clientUserId: "client-ana",
    assignedRoutineId: "ar-ana-macho",
    dayIndex: 0,
    status: "COMPLETED",
    startedAt: daysAgo(14),
    completedAt: daysAgo(14),
    totalDurationSec: 4200,
    bodyweightKg: 68.5,
    subjectiveFatigue: 3,
    notes: null,
    isFreeWorkout: false,
    setsJson: [
      { id: "s-a07-1", exerciseId: "ex-press-banca", setNumber: 1, weightKg: 32.5, reps: 10, rpe: 7, isWarmup: false, isPr: false },
      { id: "s-a07-2", exerciseId: "ex-press-banca", setNumber: 2, weightKg: 32.5, reps: 10, rpe: 8, isWarmup: false, isPr: false },
      { id: "s-a07-3", exerciseId: "ex-press-banca", setNumber: 3, weightKg: 35, reps: 9, rpe: 9, isWarmup: false, isPr: true },
    ],
  },
  {
    id: "sess-ana-08",
    clientUserId: "client-ana",
    assignedRoutineId: "ar-ana-macho",
    dayIndex: 1,
    status: "COMPLETED",
    startedAt: daysAgo(7),
    completedAt: daysAgo(7),
    totalDurationSec: 3900,
    bodyweightKg: 68.5,
    subjectiveFatigue: 2,
    notes: null,
    isFreeWorkout: false,
    setsJson: [
      { id: "s-a08-1", exerciseId: "ex-remo-mancuerna", setNumber: 1, weightKg: 14, reps: 12, rpe: 7, isWarmup: false, isPr: false },
      { id: "s-a08-2", exerciseId: "ex-remo-mancuerna", setNumber: 2, weightKg: 16, reps: 12, rpe: 8, isWarmup: false, isPr: true },
      { id: "s-a08-3", exerciseId: "ex-remo-cuello", setNumber: 1, weightKg: 15, reps: 10, rpe: 7, isWarmup: false, isPr: false },
    ],
  },
  {
    id: "sess-ana-09",
    clientUserId: "client-ana",
    assignedRoutineId: "ar-ana-macho",
    dayIndex: 2,
    status: "COMPLETED",
    startedAt: daysAgo(3),
    completedAt: daysAgo(3),
    totalDurationSec: 4500,
    bodyweightKg: 68.5,
    subjectiveFatigue: 2,
    notes: "Excelente sesión de piernas",
    isFreeWorkout: false,
    setsJson: [
      { id: "s-a09-1", exerciseId: "ex-desplante-bulgaro", setNumber: 1, weightKg: 12, reps: 12, rpe: 7, isWarmup: false, isPr: false },
      { id: "s-a09-2", exerciseId: "ex-desplante-bulgaro", setNumber: 2, weightKg: 14, reps: 12, rpe: 8, isWarmup: false, isPr: true },
      { id: "s-a09-3", exerciseId: "ex-prensa", setNumber: 1, weightKg: 90, reps: 12, rpe: 8, isWarmup: false, isPr: true },
      { id: "s-a09-4", exerciseId: "ex-prensa", setNumber: 2, weightKg: 90, reps: 10, rpe: 9, isWarmup: false, isPr: false },
    ],
  },
  // Bruno sessions — 5 sessions, Programa Macho
  {
    id: "sess-bruno-01",
    clientUserId: "client-bruno",
    assignedRoutineId: "ar-bruno-macho",
    dayIndex: 0,
    status: "COMPLETED",
    startedAt: daysAgo(26),
    completedAt: daysAgo(26),
    totalDurationSec: 4500,
    bodyweightKg: 80,
    subjectiveFatigue: 3,
    notes: null,
    isFreeWorkout: false,
    setsJson: [
      { id: "s-b01-1", exerciseId: "ex-press-banca", setNumber: 1, weightKg: 80, reps: 10, rpe: 7, isWarmup: false, isPr: false },
      { id: "s-b01-2", exerciseId: "ex-press-banca", setNumber: 2, weightKg: 80, reps: 10, rpe: 8, isWarmup: false, isPr: false },
      { id: "s-b01-3", exerciseId: "ex-aperturas", setNumber: 1, weightKg: 18, reps: 12, rpe: 7, isWarmup: false, isPr: false },
    ],
  },
  {
    id: "sess-bruno-02",
    clientUserId: "client-bruno",
    assignedRoutineId: "ar-bruno-macho",
    dayIndex: 1,
    status: "COMPLETED",
    startedAt: daysAgo(23),
    completedAt: daysAgo(23),
    totalDurationSec: 4200,
    bodyweightKg: 80.5,
    subjectiveFatigue: 3,
    notes: null,
    isFreeWorkout: false,
    setsJson: [
      { id: "s-b02-1", exerciseId: "ex-remo-mancuerna", setNumber: 1, weightKg: 28, reps: 12, rpe: 7, isWarmup: false, isPr: false },
      { id: "s-b02-2", exerciseId: "ex-remo-mancuerna", setNumber: 2, weightKg: 28, reps: 12, rpe: 8, isWarmup: false, isPr: false },
      { id: "s-b02-3", exerciseId: "ex-pullover-mancuerna", setNumber: 1, weightKg: 20, reps: 10, rpe: 7, isWarmup: false, isPr: false },
    ],
  },
  {
    id: "sess-bruno-03",
    clientUserId: "client-bruno",
    assignedRoutineId: "ar-bruno-macho",
    dayIndex: 2,
    status: "COMPLETED",
    startedAt: daysAgo(18),
    completedAt: daysAgo(18),
    totalDurationSec: 4800,
    bodyweightKg: 81,
    subjectiveFatigue: 4,
    notes: "Desplantes búlgaros al máximo hoy",
    isFreeWorkout: false,
    setsJson: [
      { id: "s-b03-1", exerciseId: "ex-desplante-bulgaro", setNumber: 1, weightKg: 22, reps: 12, rpe: 8, isWarmup: false, isPr: false },
      { id: "s-b03-2", exerciseId: "ex-desplante-bulgaro", setNumber: 2, weightKg: 24, reps: 12, rpe: 9, isWarmup: false, isPr: true },
      { id: "s-b03-3", exerciseId: "ex-prensa", setNumber: 1, weightKg: 140, reps: 12, rpe: 8, isWarmup: false, isPr: false },
    ],
  },
  {
    id: "sess-bruno-04",
    clientUserId: "client-bruno",
    assignedRoutineId: "ar-bruno-macho",
    dayIndex: 0,
    status: "COMPLETED",
    startedAt: daysAgo(12),
    completedAt: daysAgo(12),
    totalDurationSec: 4200,
    bodyweightKg: 81.5,
    subjectiveFatigue: 3,
    notes: null,
    isFreeWorkout: false,
    setsJson: [
      { id: "s-b04-1", exerciseId: "ex-press-banca", setNumber: 1, weightKg: 82.5, reps: 10, rpe: 7, isWarmup: false, isPr: false },
      { id: "s-b04-2", exerciseId: "ex-press-banca", setNumber: 2, weightKg: 82.5, reps: 10, rpe: 8, isWarmup: false, isPr: false },
      { id: "s-b04-3", exerciseId: "ex-press-militar-manc", setNumber: 1, weightKg: 18, reps: 12, rpe: 7, isWarmup: false, isPr: false },
      { id: "s-b04-4", exerciseId: "ex-press-militar-manc", setNumber: 2, weightKg: 20, reps: 10, rpe: 8, isWarmup: false, isPr: true },
    ],
  },
  {
    id: "sess-bruno-05",
    clientUserId: "client-bruno",
    assignedRoutineId: "ar-bruno-macho",
    dayIndex: 1,
    status: "COMPLETED",
    startedAt: daysAgo(5),
    completedAt: daysAgo(5),
    totalDurationSec: 4200,
    bodyweightKg: 83,
    subjectiveFatigue: 3,
    notes: null,
    isFreeWorkout: false,
    setsJson: [
      { id: "s-b05-1", exerciseId: "ex-remo-mancuerna", setNumber: 1, weightKg: 30, reps: 12, rpe: 7, isWarmup: false, isPr: false },
      { id: "s-b05-2", exerciseId: "ex-remo-mancuerna", setNumber: 2, weightKg: 30, reps: 12, rpe: 8, isWarmup: false, isPr: true },
      { id: "s-b05-3", exerciseId: "ex-curl-mancuerna", setNumber: 1, weightKg: 14, reps: 12, rpe: 7, isWarmup: false, isPr: false },
      { id: "s-b05-4", exerciseId: "ex-curl-martillo", setNumber: 1, weightKg: 14, reps: 12, rpe: 7, isWarmup: false, isPr: false },
    ],
  },
];

// ── Body metrics ──────────────────────────────────────────────────────────────

// Ana: FAT_LOSS — weight 72 → 68.5 over 12 weeks (descending)
// Bruno: MUSCLE_GAIN — weight 80 → 83 over 12 weeks (ascending)

function weeksAgo(n: number): string {
  const d = new Date("2026-05-07T08:00:00Z");
  d.setDate(d.getDate() - n * 7);
  return d.toISOString();
}

export const DEMO_METRICS: DemoMetricRow[] = [
  // Ana — 12 entries, descending weight
  { id: "m-ana-01", clientUserId: "client-ana", recordedAt: weeksAgo(11), weightKg: 72.0, bodyFatPct: 28.0, muscleMassKg: 48.0, waistCm: 80, hipCm: 98, neckCm: 34, chestCm: 88, armCm: 28, thighCm: 56, source: "MANUAL", notes: null },
  { id: "m-ana-02", clientUserId: "client-ana", recordedAt: weeksAgo(10), weightKg: 71.5, bodyFatPct: 27.5, muscleMassKg: 48.2, waistCm: 79, hipCm: 97.5, neckCm: 34, chestCm: 87, armCm: 27.5, thighCm: 55.5, source: "MANUAL", notes: null },
  { id: "m-ana-03", clientUserId: "client-ana", recordedAt: weeksAgo(9), weightKg: 71.0, bodyFatPct: 27.2, muscleMassKg: 48.3, waistCm: 78.5, hipCm: 97, neckCm: 33.5, chestCm: 87, armCm: 27.5, thighCm: 55, source: "MANUAL", notes: null },
  { id: "m-ana-04", clientUserId: "client-ana", recordedAt: weeksAgo(8), weightKg: 70.5, bodyFatPct: 26.8, muscleMassKg: 48.5, waistCm: 78, hipCm: 96.5, neckCm: 33.5, chestCm: 86.5, armCm: 27, thighCm: 55, source: "MANUAL", notes: null },
  { id: "m-ana-05", clientUserId: "client-ana", recordedAt: weeksAgo(7), weightKg: 70.2, bodyFatPct: 26.5, muscleMassKg: 48.6, waistCm: 77.5, hipCm: 96, neckCm: 33, chestCm: 86, armCm: 27, thighCm: 54.5, source: "MANUAL", notes: "Bajó bien esta semana" },
  { id: "m-ana-06", clientUserId: "client-ana", recordedAt: weeksAgo(6), weightKg: 70.0, bodyFatPct: 26.2, muscleMassKg: 48.8, waistCm: 77, hipCm: 95.5, neckCm: 33, chestCm: 85.5, armCm: 27, thighCm: 54, source: "MANUAL", notes: null },
  { id: "m-ana-07", clientUserId: "client-ana", recordedAt: weeksAgo(5), weightKg: 69.8, bodyFatPct: 26.0, muscleMassKg: 48.9, waistCm: 76.5, hipCm: 95, neckCm: 33, chestCm: 85, armCm: 27, thighCm: 54, source: "MANUAL", notes: null },
  { id: "m-ana-08", clientUserId: "client-ana", recordedAt: weeksAgo(4), weightKg: 69.5, bodyFatPct: 25.5, muscleMassKg: 49.0, waistCm: 76, hipCm: 94.5, neckCm: 32.5, chestCm: 85, armCm: 26.5, thighCm: 53.5, source: "MANUAL", notes: null },
  { id: "m-ana-09", clientUserId: "client-ana", recordedAt: weeksAgo(3), weightKg: 69.2, bodyFatPct: 25.2, muscleMassKg: 49.2, waistCm: 75.5, hipCm: 94, neckCm: 32.5, chestCm: 84.5, armCm: 26.5, thighCm: 53, source: "MANUAL", notes: null },
  { id: "m-ana-10", clientUserId: "client-ana", recordedAt: weeksAgo(2), weightKg: 69.0, bodyFatPct: 25.0, muscleMassKg: 49.3, waistCm: 75, hipCm: 93.5, neckCm: 32, chestCm: 84, armCm: 26.5, thighCm: 53, source: "MANUAL", notes: null },
  { id: "m-ana-11", clientUserId: "client-ana", recordedAt: weeksAgo(1), weightKg: 68.7, bodyFatPct: 24.5, muscleMassKg: 49.5, waistCm: 74.5, hipCm: 93, neckCm: 32, chestCm: 83.5, armCm: 26, thighCm: 52.5, source: "MANUAL", notes: "Gran progreso" },
  { id: "m-ana-12", clientUserId: "client-ana", recordedAt: weeksAgo(0), weightKg: 68.5, bodyFatPct: 24.0, muscleMassKg: 49.6, waistCm: 74, hipCm: 92.5, neckCm: 32, chestCm: 83, armCm: 26, thighCm: 52, source: "MANUAL", notes: null },
  // Bruno — 12 entries, ascending weight
  { id: "m-bruno-01", clientUserId: "client-bruno", recordedAt: weeksAgo(11), weightKg: 80.0, bodyFatPct: 18.0, muscleMassKg: 62.0, waistCm: 85, hipCm: 97, neckCm: 38, chestCm: 100, armCm: 36, thighCm: 60, source: "MANUAL", notes: null },
  { id: "m-bruno-02", clientUserId: "client-bruno", recordedAt: weeksAgo(10), weightKg: 80.3, bodyFatPct: 17.9, muscleMassKg: 62.3, waistCm: 85, hipCm: 97, neckCm: 38, chestCm: 100.5, armCm: 36.2, thighCm: 60.2, source: "MANUAL", notes: null },
  { id: "m-bruno-03", clientUserId: "client-bruno", recordedAt: weeksAgo(9), weightKg: 80.5, bodyFatPct: 17.8, muscleMassKg: 62.5, waistCm: 85, hipCm: 97.5, neckCm: 38.5, chestCm: 101, armCm: 36.5, thighCm: 60.5, source: "MANUAL", notes: null },
  { id: "m-bruno-04", clientUserId: "client-bruno", recordedAt: weeksAgo(8), weightKg: 80.8, bodyFatPct: 17.8, muscleMassKg: 62.7, waistCm: 85.5, hipCm: 97.5, neckCm: 38.5, chestCm: 101.5, armCm: 36.7, thighCm: 60.7, source: "MANUAL", notes: null },
  { id: "m-bruno-05", clientUserId: "client-bruno", recordedAt: weeksAgo(7), weightKg: 81.0, bodyFatPct: 17.7, muscleMassKg: 63.0, waistCm: 85.5, hipCm: 97.5, neckCm: 38.5, chestCm: 102, armCm: 37, thighCm: 61, source: "MANUAL", notes: null },
  { id: "m-bruno-06", clientUserId: "client-bruno", recordedAt: weeksAgo(6), weightKg: 81.3, bodyFatPct: 17.7, muscleMassKg: 63.2, waistCm: 86, hipCm: 98, neckCm: 38.5, chestCm: 102.5, armCm: 37.2, thighCm: 61.2, source: "MANUAL", notes: null },
  { id: "m-bruno-07", clientUserId: "client-bruno", recordedAt: weeksAgo(5), weightKg: 81.5, bodyFatPct: 17.6, muscleMassKg: 63.5, waistCm: 86, hipCm: 98, neckCm: 39, chestCm: 103, armCm: 37.5, thighCm: 61.5, source: "MANUAL", notes: "Ganando masa" },
  { id: "m-bruno-08", clientUserId: "client-bruno", recordedAt: weeksAgo(4), weightKg: 81.8, bodyFatPct: 17.6, muscleMassKg: 63.7, waistCm: 86, hipCm: 98.5, neckCm: 39, chestCm: 103.5, armCm: 37.7, thighCm: 61.7, source: "MANUAL", notes: null },
  { id: "m-bruno-09", clientUserId: "client-bruno", recordedAt: weeksAgo(3), weightKg: 82.0, bodyFatPct: 17.5, muscleMassKg: 64.0, waistCm: 86.5, hipCm: 98.5, neckCm: 39, chestCm: 104, armCm: 38, thighCm: 62, source: "MANUAL", notes: null },
  { id: "m-bruno-10", clientUserId: "client-bruno", recordedAt: weeksAgo(2), weightKg: 82.3, bodyFatPct: 17.5, muscleMassKg: 64.2, waistCm: 86.5, hipCm: 98.5, neckCm: 39, chestCm: 104.5, armCm: 38.2, thighCm: 62.2, source: "MANUAL", notes: null },
  { id: "m-bruno-11", clientUserId: "client-bruno", recordedAt: weeksAgo(1), weightKg: 82.7, bodyFatPct: 17.5, muscleMassKg: 64.5, waistCm: 87, hipCm: 99, neckCm: 39.5, chestCm: 105, armCm: 38.5, thighCm: 62.5, source: "MANUAL", notes: null },
  { id: "m-bruno-12", clientUserId: "client-bruno", recordedAt: weeksAgo(0), weightKg: 83.0, bodyFatPct: 17.5, muscleMassKg: 64.8, waistCm: 87, hipCm: 99, neckCm: 39.5, chestCm: 105.5, armCm: 38.7, thighCm: 62.7, source: "MANUAL", notes: null },
];

// ── Locations ─────────────────────────────────────────────────────────────────

export const DEMO_LOCATIONS: DemoLocationRow[] = [
  {
    id: "loc-gym-central",
    trainerUserId: DEMO_TRAINER_ID,
    name: "Gym Central San José",
    address: "Av. 2, Calle 5, San José",
    kind: "GYM",
    costModel: "FLAT",
    costPerVisitCRC: 3000,
    costPerKmCRC: null,
    defaultKm: null,
    monthlyRentCRC: 45000,
    notes: "Gimnasio principal donde entreno la mayoría de clientes.",
  },
  {
    id: "loc-home",
    trainerUserId: DEMO_TRAINER_ID,
    name: "Estudio en casa",
    address: "Barrio Escalante, San José",
    kind: "HOME",
    costModel: "FLAT",
    costPerVisitCRC: 0,
    costPerKmCRC: null,
    defaultKm: null,
    monthlyRentCRC: null,
    notes: "Para sesiones online y clientes que vienen a casa.",
  },
];

// ── Location visits (16 total) ────────────────────────────────────────────────

function isoDate(daysBack: number): string {
  const d = new Date("2026-05-07T09:00:00Z");
  d.setDate(d.getDate() - daysBack);
  return d.toISOString();
}

export const DEMO_LOCATION_VISITS: DemoLocationVisitRow[] = Array.from({ length: 16 }, (_, i) => ({
  id: `lv-${String(i + 1).padStart(3, "0")}`,
  trainerUserId: DEMO_TRAINER_ID,
  locationId: i % 4 === 3 ? "loc-home" : "loc-gym-central",
  visitedAt: isoDate(i * 2),
  kmTraveled: null,
  computedCostCRC: i % 4 === 3 ? 0 : 3000,
  notes: null,
}));

// ── Expenses ──────────────────────────────────────────────────────────────────

export const DEMO_EXPENSES: DemoExpenseRow[] = [
  // ── Abril 2026 ───────────────────────────────────────────────────────────────
  {
    id: "exp-001",
    trainerUserId: DEMO_TRAINER_ID,
    occurredAt: isoDate(36),
    amountCRC: 45000,
    category: "ALQUILER_ESPACIO",
    locationId: "loc-gym-central",
    description: "Alquiler mensual Gym Central — abril 2026",
    source: "MANUAL",
    visitId: null,
  },
  {
    id: "exp-002",
    trainerUserId: DEMO_TRAINER_ID,
    occurredAt: isoDate(36),
    amountCRC: 18500,
    category: "SOFTWARE",
    locationId: null,
    description: "Suscripción Vizion Pro — abril 2026",
    source: "MANUAL",
    visitId: null,
  },
  {
    id: "exp-apr-003",
    trainerUserId: DEMO_TRAINER_ID,
    occurredAt: isoDate(34),
    amountCRC: 12000,
    category: "IMPUESTOS",
    locationId: null,
    description: "Cuota CCSS — abril 2026",
    source: "MANUAL",
    visitId: null,
  },
  {
    id: "exp-apr-004",
    trainerUserId: DEMO_TRAINER_ID,
    occurredAt: isoDate(28),
    amountCRC: 8000,
    category: "MARKETING",
    locationId: null,
    description: "Meta Ads — campaña abril 2026",
    source: "MANUAL",
    visitId: null,
  },
  {
    id: "exp-apr-005",
    trainerUserId: DEMO_TRAINER_ID,
    occurredAt: isoDate(20),
    amountCRC: 6000,
    category: "TRANSPORTE",
    locationId: "loc-gym-central",
    description: "Transporte Gym Central — semana 3 abril",
    source: "MANUAL",
    visitId: null,
  },
  {
    id: "exp-apr-006",
    trainerUserId: DEMO_TRAINER_ID,
    occurredAt: isoDate(15),
    amountCRC: 15000,
    category: "EQUIPO",
    locationId: null,
    description: "Bandas de resistencia + guantes — abril",
    source: "MANUAL",
    visitId: null,
  },
  {
    id: "exp-apr-007",
    trainerUserId: DEMO_TRAINER_ID,
    occurredAt: isoDate(12),
    amountCRC: 25000,
    category: "SERVICIOS_PROFESIONALES",
    locationId: null,
    description: "Honorarios contador — revisión planillas",
    source: "MANUAL",
    visitId: null,
  },
  {
    id: "exp-apr-008",
    trainerUserId: DEMO_TRAINER_ID,
    occurredAt: isoDate(10),
    amountCRC: 4500,
    category: "COMIDAS",
    locationId: null,
    description: "Almuerzo con cliente nuevo — abril",
    source: "MANUAL",
    visitId: null,
  },
  // ── Mayo 2026 ────────────────────────────────────────────────────────────────
  {
    id: "exp-003",
    trainerUserId: DEMO_TRAINER_ID,
    occurredAt: isoDate(6),
    amountCRC: 45000,
    category: "ALQUILER_ESPACIO",
    locationId: "loc-gym-central",
    description: "Alquiler mensual Gym Central — mayo 2026",
    source: "MANUAL",
    visitId: null,
  },
  {
    id: "exp-004",
    trainerUserId: DEMO_TRAINER_ID,
    occurredAt: isoDate(6),
    amountCRC: 18500,
    category: "SOFTWARE",
    locationId: null,
    description: "Suscripción Vizion Pro — mayo 2026",
    source: "MANUAL",
    visitId: null,
  },
  {
    id: "exp-005",
    trainerUserId: DEMO_TRAINER_ID,
    occurredAt: isoDate(5),
    amountCRC: 35000,
    category: "EDUCACION",
    locationId: null,
    description: "Curso certificación nutrición deportiva",
    source: "MANUAL",
    visitId: null,
  },
  {
    id: "exp-006",
    trainerUserId: DEMO_TRAINER_ID,
    occurredAt: isoDate(4),
    amountCRC: 15000,
    category: "MARKETING",
    locationId: null,
    description: "Meta Ads — campaña mayo 2026",
    source: "MANUAL",
    visitId: null,
  },
  {
    id: "exp-007",
    trainerUserId: DEMO_TRAINER_ID,
    occurredAt: isoDate(3),
    amountCRC: 12000,
    category: "EQUIPO",
    locationId: null,
    description: "Bandas de resistencia y accesorios para clientes",
    source: "MANUAL",
    visitId: null,
  },
  {
    id: "exp-008",
    trainerUserId: DEMO_TRAINER_ID,
    occurredAt: isoDate(2),
    amountCRC: 8500,
    category: "TRANSPORTE",
    locationId: "loc-gym-central",
    description: "Transporte visitas Gym Central — semana 1 mayo",
    source: "MANUAL",
    visitId: null,
  },
  {
    id: "exp-009",
    trainerUserId: DEMO_TRAINER_ID,
    occurredAt: isoDate(1),
    amountCRC: 6000,
    category: "COMIDAS",
    locationId: null,
    description: "Almuerzo reunión con cliente prospecto",
    source: "MANUAL",
    visitId: null,
  },
  {
    id: "exp-010",
    trainerUserId: DEMO_TRAINER_ID,
    occurredAt: isoDate(0),
    amountCRC: 12000,
    category: "IMPUESTOS",
    locationId: null,
    description: "Cuota CCSS — mayo 2026",
    source: "MANUAL",
    visitId: null,
  },
  {
    id: "exp-011",
    trainerUserId: DEMO_TRAINER_ID,
    occurredAt: isoDate(0),
    amountCRC: 25000,
    category: "SERVICIOS_PROFESIONALES",
    locationId: null,
    description: "Honorarios contador — declaración mensual mayo",
    source: "MANUAL",
    visitId: null,
  },
  {
    id: "exp-012",
    trainerUserId: DEMO_TRAINER_ID,
    occurredAt: isoDate(0),
    amountCRC: 5000,
    category: "OTROS",
    locationId: null,
    description: "Material de limpieza y desinfectante estudio",
    source: "MANUAL",
    visitId: null,
  },
];

// ── Sales (3 one-off — abril) ─────────────────────────────────────────────────

export const DEMO_SALES: DemoSaleRow[] = [
  // ── Abril 2026 ──────────────────────────────────────────────────────────────
  {
    id: "sale-001",
    trainerUserId: DEMO_TRAINER_ID,
    clientUserId: "client-ana",
    occurredAt: isoDate(25),
    amountCRC: 75000,
    category: "SESION_PT",
    description: "Mensualidad Ana Solís — abril 2026",
    paymentMethod: "SINPE",
    paidStatus: "PAID",
  },
  {
    id: "sale-002",
    trainerUserId: DEMO_TRAINER_ID,
    clientUserId: "client-bruno",
    occurredAt: isoDate(24),
    amountCRC: 80000,
    category: "SESION_PT",
    description: "Mensualidad Bruno Jiménez — abril 2026",
    paymentMethod: "SINPE",
    paidStatus: "PAID",
  },
  {
    id: "sale-apr-003",
    trainerUserId: DEMO_TRAINER_ID,
    clientUserId: "client-carlos",
    occurredAt: isoDate(34),
    amountCRC: 65000,
    category: "SESION_PT",
    description: "Mensualidad Carlos Ulate — abril 2026",
    paymentMethod: "SINPE",
    paidStatus: "PAID",
  },
  {
    id: "sale-apr-004",
    trainerUserId: DEMO_TRAINER_ID,
    clientUserId: "client-diana",
    occurredAt: isoDate(33),
    amountCRC: 70000,
    category: "SESION_PT",
    description: "Mensualidad Diana Mora — abril 2026",
    paymentMethod: "SINPE",
    paidStatus: "PAID",
  },
  {
    id: "sale-003",
    trainerUserId: DEMO_TRAINER_ID,
    clientUserId: null,
    occurredAt: isoDate(10),
    amountCRC: 25000,
    category: "EVALUACION_INICIAL",
    description: "Evaluación inicial nuevo cliente referido",
    paymentMethod: "EFECTIVO",
    paidStatus: "PAID",
  },
  {
    id: "sale-apr-005",
    trainerUserId: DEMO_TRAINER_ID,
    clientUserId: "client-ana",
    occurredAt: isoDate(18),
    amountCRC: 18000,
    category: "PLAN_NUTRICIONAL",
    description: "Plan nutricional mes 2 — Ana Solís",
    paymentMethod: "SINPE",
    paidStatus: "PAID",
  },
  {
    id: "sale-apr-006",
    trainerUserId: DEMO_TRAINER_ID,
    clientUserId: null,
    occurredAt: isoDate(14),
    amountCRC: 20000,
    category: "CLASE_GRUPAL",
    description: "Clase grupal Sábado 26 abril (5 personas)",
    paymentMethod: "EFECTIVO",
    paidStatus: "PAID",
  },
  // ── Mayo 2026 ────────────────────────────────────────────────────────────────
  {
    id: "sale-004",
    trainerUserId: DEMO_TRAINER_ID,
    clientUserId: "client-ana",
    occurredAt: isoDate(6),
    amountCRC: 75000,
    category: "SESION_PT",
    description: "Mensualidad Ana Solís — mayo 2026",
    paymentMethod: "SINPE",
    paidStatus: "PAID",
  },
  {
    id: "sale-005",
    trainerUserId: DEMO_TRAINER_ID,
    clientUserId: "client-bruno",
    occurredAt: isoDate(5),
    amountCRC: 80000,
    category: "SESION_PT",
    description: "Mensualidad Bruno Jiménez — mayo 2026",
    paymentMethod: "SINPE",
    paidStatus: "PAID",
  },
  {
    id: "sale-006",
    trainerUserId: DEMO_TRAINER_ID,
    clientUserId: "client-carlos",
    occurredAt: isoDate(4),
    amountCRC: 65000,
    category: "SESION_PT",
    description: "Mensualidad Carlos Ulate — mayo 2026",
    paymentMethod: "SINPE",
    paidStatus: "PAID",
  },
  {
    id: "sale-007",
    trainerUserId: DEMO_TRAINER_ID,
    clientUserId: "client-diana",
    occurredAt: isoDate(3),
    amountCRC: 70000,
    category: "SESION_PT",
    description: "Mensualidad Diana Mora — mayo 2026",
    paymentMethod: "SINPE",
    paidStatus: "PAID",
  },
  {
    id: "sale-008",
    trainerUserId: DEMO_TRAINER_ID,
    clientUserId: null,
    occurredAt: isoDate(2),
    amountCRC: 25000,
    category: "EVALUACION_INICIAL",
    description: "Evaluación inicial — prospecto referido por Bruno",
    paymentMethod: "EFECTIVO",
    paidStatus: "PAID",
  },
  {
    id: "sale-009",
    trainerUserId: DEMO_TRAINER_ID,
    clientUserId: "client-ana",
    occurredAt: isoDate(1),
    amountCRC: 15000,
    category: "PLAN_NUTRICIONAL",
    description: "Plan nutricional personalizado — Ana Solís",
    paymentMethod: "SINPE",
    paidStatus: "PAID",
  },
  {
    id: "sale-010",
    trainerUserId: DEMO_TRAINER_ID,
    clientUserId: null,
    occurredAt: isoDate(0),
    amountCRC: 20000,
    category: "CLASE_GRUPAL",
    description: "Clase grupal HIIT (4 personas) — viernes 8 mayo",
    paymentMethod: "EFECTIVO",
    paidStatus: "PAID",
  },
  {
    id: "sale-011",
    trainerUserId: DEMO_TRAINER_ID,
    clientUserId: "client-carlos",
    occurredAt: isoDate(1),
    amountCRC: 35000,
    category: "ASESORIA_ONLINE",
    description: "Asesoría online + ajuste de macros — Carlos Ulate",
    paymentMethod: "SINPE",
    paidStatus: "PAID",
  },
  {
    id: "sale-012",
    trainerUserId: DEMO_TRAINER_ID,
    clientUserId: "client-bruno",
    occurredAt: isoDate(2),
    amountCRC: 12000,
    category: "PRODUCTO",
    description: "Shaker + banda de resistencia — Bruno Jiménez",
    paymentMethod: "EFECTIVO",
    paidStatus: "PAID",
  },
  {
    id: "sale-013",
    trainerUserId: DEMO_TRAINER_ID,
    clientUserId: null,
    occurredAt: isoDate(3),
    amountCRC: 24000,
    category: "CLASE_GRUPAL",
    description: "Clase grupal Core & Cardio (4 personas) — miér 5 mayo",
    paymentMethod: "EFECTIVO",
    paidStatus: "PAID",
  },
];
